version: '3.1'
services:
  springapp:
    image: mylandmarktech/spring-boot-mongo
    restart: always
    ports:
      - 3000:8080 
    networks:
      - amazon    
    environment:
      - MONGO_DB_HOSTNAME=mongo
      - MONGO_DB_USERNAME=proddb
      - MONGO_DB_PASSWORD=prod@123      
  mongo:  
    image: mongo 
    restart: always
    volumes:
      - data28:/data/db   
    networks:
      - amazon     
    environment:
      - MONGO_INITDB_ROOT_USERNAME=proddb
      - MONGO_INITDB_ROOT_PASSWORD=prod@123      
volumes:
  data28:
    driver: local
networks:
  amazon:
    driver: bridge
